/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen.pkg2_carlosromero;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Will
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdPlaneta = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        tfNombrePlaneta = new javax.swing.JTextField();
        spTemp = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbbAnillos = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        tfTipoSuperficie = new javax.swing.JTextField();
        spDistancia = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        jbGuardarPlaneta = new javax.swing.JButton();
        jbModificarPlaneta = new javax.swing.JButton();
        jdAstronautas = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        tfNombreAstro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spPeso = new javax.swing.JSpinner();
        tfExperiencia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfNacionalidad = new javax.swing.JTextField();
        spSueldo = new javax.swing.JSpinner();
        cbbSexo = new javax.swing.JComboBox<>();
        jbGuardarAstro = new javax.swing.JButton();
        jbModificarAstro = new javax.swing.JButton();
        ppMenuAstro = new javax.swing.JPopupMenu();
        jmiModificar = new javax.swing.JMenuItem();
        jmiEliminar = new javax.swing.JMenuItem();
        ppMenuPlanet = new javax.swing.JPopupMenu();
        jmiModificar1 = new javax.swing.JMenuItem();
        jmiEliminar1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jbAstro = new javax.swing.JButton();
        jbPlaneta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbbTipoNave = new javax.swing.JComboBox<>();
        tfMaterialNave = new javax.swing.JTextField();
        tfLugarDespeje1 = new javax.swing.JTextField();
        spVelocidadNave = new javax.swing.JSpinner();
        tfNumeroDeSerie = new javax.swing.JTextField();
        cbbAstronautas = new javax.swing.JComboBox<>();
        cbbPlanetaDestino = new javax.swing.JComboBox<>();
        spPesoNave = new javax.swing.JSpinner();
        jbPlaneta1 = new javax.swing.JButton();
        AgregarA = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAstronautas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePlanetas = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbbExpedicionNave = new javax.swing.JComboBox<>();
        cbbExpedicionPlanetaDestino1 = new javax.swing.JComboBox<>();
        jbPlaneta2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        spRegreso = new javax.swing.JSpinner();
        spIda1 = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jdPlaneta.setMaximumSize(new java.awt.Dimension(600, 400));
        jdPlaneta.setMinimumSize(new java.awt.Dimension(600, 400));
        jdPlaneta.setPreferredSize(new java.awt.Dimension(600, 400));
        jdPlaneta.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("Nombre: ");
        jdPlaneta.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 20));
        jdPlaneta.getContentPane().add(tfNombrePlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 370, -1));

        spTemp.setModel(new javax.swing.SpinnerNumberModel());
        jdPlaneta.getContentPane().add(spTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 240, -1));

        jLabel21.setText("Temperatura:");
        jdPlaneta.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 20));

        jLabel22.setText("Tiene Anillos?:");
        jdPlaneta.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 20));

        cbbAnillos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        jdPlaneta.getContentPane().add(cbbAnillos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, -1));

        jLabel23.setText("Tipo De Superficie:");
        jdPlaneta.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, 20));
        jdPlaneta.getContentPane().add(tfTipoSuperficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 370, -1));

        spDistancia.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 100.0d));
        jdPlaneta.getContentPane().add(spDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, -1));

        jLabel24.setText("Distancia a la Tierra:");
        jdPlaneta.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 20));

        jbGuardarPlaneta.setText("Guardar");
        jbGuardarPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbGuardarPlanetaMouseClicked(evt);
            }
        });
        jdPlaneta.getContentPane().add(jbGuardarPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jbModificarPlaneta.setText("Modificar");
        jbModificarPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbModificarPlanetaMouseClicked(evt);
            }
        });
        jdPlaneta.getContentPane().add(jbModificarPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jdAstronautas.setMaximumSize(new java.awt.Dimension(600, 400));
        jdAstronautas.setMinimumSize(new java.awt.Dimension(600, 400));
        jdAstronautas.setPreferredSize(new java.awt.Dimension(600, 400));
        jdAstronautas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Sueldo");
        jdAstronautas.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 20));
        jdAstronautas.getContentPane().add(tfNombreAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 370, -1));

        jLabel6.setText("Nombre: ");
        jdAstronautas.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 20));

        jLabel7.setText("Nacionalidad:");
        jdAstronautas.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 20));

        jLabel11.setText("Peso:");
        jdAstronautas.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 20));

        spPeso.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 100.0d));
        jdAstronautas.getContentPane().add(spPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, -1));
        jdAstronautas.getContentPane().add(tfExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 370, -1));

        jLabel9.setText("Experiencia:");
        jdAstronautas.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, 20));
        jdAstronautas.getContentPane().add(tfNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 370, -1));

        spSueldo.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 100.0d));
        jdAstronautas.getContentPane().add(spSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, -1));

        cbbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maculino", "Femenino" }));
        jdAstronautas.getContentPane().add(cbbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, -1));

        jbGuardarAstro.setText("Guardar");
        jbGuardarAstro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbGuardarAstroMouseClicked(evt);
            }
        });
        jdAstronautas.getContentPane().add(jbGuardarAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jbModificarAstro.setText("Modificar");
        jbModificarAstro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbModificarAstroMouseClicked(evt);
            }
        });
        jdAstronautas.getContentPane().add(jbModificarAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jmiModificar.setText("Modificar Astronauta");
        jmiModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificarActionPerformed(evt);
            }
        });
        ppMenuAstro.add(jmiModificar);

        jmiEliminar.setText("Eliminar Astronauta");
        jmiEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarActionPerformed(evt);
            }
        });
        ppMenuAstro.add(jmiEliminar);

        jmiModificar1.setText("Modificar Planeta");
        jmiModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiModificar1ActionPerformed(evt);
            }
        });
        ppMenuPlanet.add(jmiModificar1);

        jmiEliminar1.setText("Eliminar Planeta");
        jmiEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminar1ActionPerformed(evt);
            }
        });
        ppMenuPlanet.add(jmiEliminar1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbAstro.setText("Agregar Atronauta");
        jbAstro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAstroMouseClicked(evt);
            }
        });
        jPanel1.add(jbAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 180, -1));

        jbPlaneta.setText("Agregar Planeta");
        jbPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPlanetaMouseClicked(evt);
            }
        });
        jPanel1.add(jbPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 180, -1));

        jTabbedPane1.addTab(" Registro", jPanel1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Planeta de Destino:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 20));

        jLabel13.setText("Numero de Serie:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 20));

        jLabel14.setText("Velocidad:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, 20));

        jLabel15.setText("Tipo de Nave:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 110, 20));

        jLabel16.setText("Peso de Nave");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 20));

        jLabel17.setText("Material");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 20));

        jLabel18.setText("Astronautas:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 110, 20));

        jLabel19.setText("Lugar Despeje:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 110, 20));

        cbbTipoNave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sonda Espacial", "Nave Tripulada" }));
        cbbTipoNave.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTipoNaveItemStateChanged(evt);
            }
        });
        jPanel3.add(cbbTipoNave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, -1));
        jPanel3.add(tfMaterialNave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 160, -1));
        jPanel3.add(tfLugarDespeje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 160, -1));

        spVelocidadNave.setModel(new javax.swing.SpinnerNumberModel());
        jPanel3.add(spVelocidadNave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));
        jPanel3.add(tfNumeroDeSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 370, -1));

        jPanel3.add(cbbAstronautas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 180, -1));

        jPanel3.add(cbbPlanetaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 180, -1));

        spPesoNave.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 100.0d));
        jPanel3.add(spPesoNave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 160, -1));

        jbPlaneta1.setText("Crear Nave");
        jPanel3.add(jbPlaneta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 180, -1));

        AgregarA.setText("Agregar A.");
        jPanel3.add(AgregarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        jTabbedPane1.addTab(" Crear Nave", jPanel3);

        tableAstronautas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nacionalidad", "Sueldo", "Experencia", "Sexo", "Peso"
            }
        ));
        tableAstronautas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAstronautasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAstronautas);

        tablePlanetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Temperatura", "Anillos", "Tipo de Superficie", "Distancia a la Tierra"
            }
        ));
        tablePlanetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePlanetasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablePlanetas);

        jLabel27.setText("Planetas");

        jLabel28.setText("Astronautas:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(76, 76, 76)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Listar Elemetos", jPanel5);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setText("Nave:");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 110, 20));

        jLabel26.setText("Timepo Ida:");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, 20));

        jPanel4.add(cbbExpedicionNave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 180, -1));

        jPanel4.add(cbbExpedicionPlanetaDestino1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 180, -1));

        jbPlaneta2.setText("Crear Expedicion");
        jPanel4.add(jbPlaneta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 180, -1));

        jLabel29.setText("Timepo Regreso:");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 110, 20));

        jLabel30.setText("Planeta de Destino:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 20));

        spRegreso.setModel(new javax.swing.SpinnerNumberModel());
        jPanel4.add(spRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 180, -1));

        spIda1.setModel(new javax.swing.SpinnerNumberModel());
        jPanel4.add(spIda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 180, -1));

        jTabbedPane1.addTab(" Crear Expedicion", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPlanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPlanetaMouseClicked
        jbGuardarPlaneta.setVisible(true);
        jbModificarPlaneta.setVisible(false);
        jdPlaneta.setModal(true);
        jdPlaneta.pack();
        jdPlaneta.setLocationRelativeTo(this);
        jdPlaneta.setVisible(true);
    }//GEN-LAST:event_jbPlanetaMouseClicked

    private void jbAstroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAstroMouseClicked
        jbGuardarAstro.setVisible(true);
        jbModificarAstro.setVisible(false);
        jdAstronautas.setModal(true);
        jdAstronautas.pack();
        jdAstronautas.setLocationRelativeTo(this);
        jdAstronautas.setVisible(true);
    }//GEN-LAST:event_jbAstroMouseClicked

    private void jbGuardarPlanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGuardarPlanetaMouseClicked
        String NombrePlaneta = tfNombrePlaneta.getText();
        int TemperaturaMedia = Integer.parseInt(spTemp.getValue().toString());
        String Anillos = cbbAnillos.getSelectedItem().toString();
        String TipoDeSuperficie = tfTipoSuperficie.getText();
        double DistanciaATierra = Double.parseDouble(spDistancia.getValue().toString());

        Planetas planet = new Planetas(NombrePlaneta, TemperaturaMedia, Anillos, TipoDeSuperficie, DistanciaATierra);
        Planetas.add(planet);

        DefaultTableModel modelo = (DefaultTableModel) tablePlanetas.getModel();
        Object[] newRow = {NombrePlaneta, TemperaturaMedia, Anillos, TipoDeSuperficie, DistanciaATierra};
        modelo.addRow(newRow);
        tablePlanetas.setModel(modelo);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbPlanetaDestino.getModel();
        model.addElement(planet);
        cbbPlanetaDestino.setModel(model);
        cbbExpedicionPlanetaDestino1.setModel(model);
        JOptionPane.showMessageDialog(this, "Planeta Guardado", "Planeta Guardado", 1);
        tfNombrePlaneta.setText("");
        spTemp.setValue(0);
        cbbAnillos.setSelectedIndex(0);
        tfTipoSuperficie.setText("");
        spDistancia.setValue(0);
    }//GEN-LAST:event_jbGuardarPlanetaMouseClicked

    private void jbModificarPlanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbModificarPlanetaMouseClicked
        try {
            String NombrePlaneta = tfNombrePlaneta.getText();
            int TemperaturaMedia = Integer.parseInt(spTemp.getValue().toString());
            String Anillos = cbbAnillos.getSelectedItem().toString();
            String TipoDeSuperficie = tfTipoSuperficie.getText();
            double DistanciaATierra = Double.parseDouble(spDistancia.getValue().toString());
            int x = Planetas.indexOf(planetaseleccion);
            System.out.println(x);
            planetaseleccion.setNombrePlaneta(NombrePlaneta);
            planetaseleccion.setAnillos(Anillos);
            planetaseleccion.setDistanciaATierra(DistanciaATierra);
            planetaseleccion.setTemperaturaMedia(TemperaturaMedia);
            planetaseleccion.setTipoDeSuperficie(TipoDeSuperficie);
            Planetas.set(x, planetaseleccion);
            System.out.println(Planetas);
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (Planetas t : Planetas) {
                model.addElement(t);
            }
            Actualizar();
            cbbPlanetaDestino.setModel(model);
            cbbExpedicionPlanetaDestino1.setModel(model);
            tfNombrePlaneta.setText("");
            spTemp.setValue(0);
            cbbAnillos.setSelectedIndex(0);
            tfTipoSuperficie.setText("");
            spDistancia.setValue(0);
            JOptionPane.showMessageDialog(this, "Modificado", "Modificado", 1);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbModificarPlanetaMouseClicked

    private void jbGuardarAstroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbGuardarAstroMouseClicked
        String NombreAstronuta = tfNombreAstro.getText();
        String Nacinalidad = tfNacionalidad.getText();
        double Sueldo = Double.parseDouble(spSueldo.getValue().toString());
        String Experiecia = tfExperiencia.getText();
        String Sexo = cbbSexo.getSelectedItem().toString();
        double Peso = Double.parseDouble(spPeso.getValue().toString());
        Astronautas astro = new Astronautas(NombreAstronuta, Nacinalidad, Sueldo, Experiecia, Sexo, Peso);
        Astronautas.add(astro);
        DefaultTableModel modelo = (DefaultTableModel) tableAstronautas.getModel();
        Object[] newRow = {NombreAstronuta, Nacinalidad, Sueldo, Experiecia, Sexo, Peso};
        modelo.addRow(newRow);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbbAstronautas.getModel();
        model.addElement(astro);
        cbbAstronautas.setModel(model);
        JOptionPane.showMessageDialog(this, "Astronauta Guardado", "Astronauta Guardado", 1);
        tfNacionalidad.setText("");
        tfNacionalidad.setText("");
        spSueldo.setValue(0);
        tfExperiencia.setText("");
        cbbSexo.setSelectedIndex(0);
        spPeso.setValue(0);
    }//GEN-LAST:event_jbGuardarAstroMouseClicked

    private void tablePlanetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePlanetasMouseClicked
        if (evt.isMetaDown()) {
            ppMenuPlanet.show(tablePlanetas, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tablePlanetasMouseClicked

    private void tableAstronautasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAstronautasMouseClicked
        if (evt.isMetaDown()) {
            ppMenuAstro.show(tableAstronautas, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tableAstronautasMouseClicked

    private void jmiEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarActionPerformed
        try {
            int selecion = tableAstronautas.getSelectedRow();
            System.out.println(selecion);
            DefaultTableModel modelo = (DefaultTableModel) tableAstronautas.getModel();
            modelo.removeRow(selecion);
            tableAstronautas.setModel(modelo);
            this.repaint();
            Astronautas.remove(selecion);
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (Object t : Astronautas) {
                model.addElement(t);
            }
            cbbAstronautas.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No Hay Astronauta Seleccionado!", "Error", 0);
        }
    }//GEN-LAST:event_jmiEliminarActionPerformed

    private void jmiEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminar1ActionPerformed
        try {
            int selecion = tablePlanetas.getSelectedRow();
            System.out.println(selecion);
            DefaultTableModel modelo = (DefaultTableModel) tablePlanetas.getModel();
            modelo.removeRow(selecion);
            tablePlanetas.setModel(modelo);
            this.repaint();
            Planetas.remove(selecion);
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            for (Object t : Planetas) {
                model.addElement(t);
            }
            cbbPlanetaDestino.setModel(model);
            cbbExpedicionPlanetaDestino1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No Hay Planeta Seleccionado!", "Error", 0);
        }
    }//GEN-LAST:event_jmiEliminar1ActionPerformed

    private void jmiModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificarActionPerformed
        try {
            int selecion = tableAstronautas.getSelectedRow();
            astroseleccion = Astronautas.get(selecion);
            jbGuardarAstro.setVisible(false);
            jbModificarAstro.setVisible(true);
            jdAstronautas.setModal(true);
            jdAstronautas.pack();
            jdAstronautas.setLocationRelativeTo(this);
            jdAstronautas.setVisible(true);
//            tfNacionalidad.setText(astroseleccion.getNacinalidad());
//            tfNombreAstro.setText(astroseleccion.getNombreAstronuta());
//            spSueldo.setValue(astroseleccion.getSueldo());
//            tfExperiencia.setText(astroseleccion.getExperiecia());
//            if (astroseleccion.getSexo().equals("Maculino")) {
//                cbbSexo.setSelectedIndex(0);
//            } else {
//                cbbSexo.setSelectedIndex(1);
//            }
//            spPeso.setValue(astroseleccion.getPeso());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No Hay Astronauta Seleccionado!", "Error", 0);
        }
    }//GEN-LAST:event_jmiModificarActionPerformed

    private void jmiModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiModificar1ActionPerformed
        try {
            int selecion = tablePlanetas.getSelectedRow();
            planetaseleccion = Planetas.get(selecion);
            jbGuardarPlaneta.setVisible(false);
            jbModificarPlaneta.setVisible(true);
            jdPlaneta.setModal(true);
            jdPlaneta.pack();
            jdPlaneta.setLocationRelativeTo(this);
            jdPlaneta.setVisible(true);
//            tfNombrePlaneta.setText(planetaseleccion.getNombrePlaneta());
//            spTemp.setValue(planetaseleccion.getTemperaturaMedia());
//            if (planetaseleccion.getAnillos().equals("No")) {
//                cbbAnillos.setSelectedIndex(1);
//            } else {
//                cbbAnillos.setSelectedIndex(0);
//            }
//            tfTipoSuperficie.setText(planetaseleccion.getTipoDeSuperficie());
//            spDistancia.setValue(planetaseleccion.getDistanciaATierra());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No Hay Planeta Seleccionado!", "Error", 0);
        }
    }//GEN-LAST:event_jmiModificar1ActionPerformed

    private void cbbTipoNaveItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTipoNaveItemStateChanged
        if(cbbTipoNave.getSelectedIndex()==0){
            tfMaterialNave.setVisible(true);
            spPesoNave.setVisible(true);
            tfLugarDespeje1.setVisible(false);
            cbbAstronautas.setVisible(false);
            AgregarA.setVisible(false);
        }else{
            tfMaterialNave.setVisible(false);
            spPesoNave.setVisible(false);
            tfLugarDespeje1.setVisible(true);
            cbbAstronautas.setVisible(true);
            AgregarA.setVisible(true);
        }
    }//GEN-LAST:event_cbbTipoNaveItemStateChanged

    private void jbModificarAstroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbModificarAstroMouseClicked
        String NombreAstronuta = tfNombreAstro.getText();
        String Nacinalidad = tfNacionalidad.getText();
        double Sueldo = Double.parseDouble(spSueldo.getValue().toString());
        String Experiecia = tfExperiencia.getText();
        String Sexo = cbbSexo.getSelectedItem().toString();
        double Peso = Double.parseDouble(spPeso.getValue().toString());
        int x=Astronautas.indexOf(astroseleccion);
        astroseleccion.setExperiecia(Experiecia);
        astroseleccion.setNacinalidad(Nacinalidad);
        astroseleccion.setNombreAstronuta(NombreAstronuta);
        astroseleccion.setPeso(Peso);
        astroseleccion.setSexo(Sexo);
        astroseleccion.setSueldo(Sueldo);
        Astronautas.set(x, astroseleccion);
        System.out.println(Astronautas);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Astronautas t : Astronautas) {
            model.addElement(t);
        }
        Actualizar();
        cbbAstronautas.setModel(model);
        JOptionPane.showMessageDialog(this, "Modificado", "Modificado", 1);
        tfNacionalidad.setText("");
        tfNacionalidad.setText("");
        spSueldo.setValue(0);
        tfExperiencia.setText("");
        cbbSexo.setSelectedIndex(0);
        spPeso.setValue(0);
    }//GEN-LAST:event_jbModificarAstroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void Actualizar(){
        tableAstronautas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nombre", "Nacioalidad", "Sueldo", "Experiencia","Sexo","Peso"
            }
        ) {
        });
               DefaultTableModel Modelo = (DefaultTableModel) tableAstronautas.getModel();         

        for (Astronautas Astro :  Astronautas) {
            Object[] newrow = {Astro.getNombreAstronuta(), Astro.getNacinalidad(),Astro.getSueldo(), Astro.getExperiecia(), Astro.getSexo(),Astro.getPeso()
            };
            Modelo.addRow(newrow);
        }
        tableAstronautas.setModel(Modelo);
        
        
        
        tablePlanetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Nombre", "Temperatura", "Anillos", "Tipo de Superficie","Distancia a Tierra"
            }
        ) {
        });
        DefaultTableModel Modelo1 = (DefaultTableModel) tablePlanetas.getModel();
        for (Planetas t : Planetas) {
            Object [] newrow={t.getNombrePlaneta(),t.getTemperaturaMedia(),t.getAnillos(),t.getTipoDeSuperficie(),t.getDistanciaATierra()};
            Modelo1.addRow(newrow);
        }
        tablePlanetas.setModel(Modelo1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarA;
    private javax.swing.JComboBox<String> cbbAnillos;
    private javax.swing.JComboBox<String> cbbAstronautas;
    private javax.swing.JComboBox<String> cbbExpedicionNave;
    private javax.swing.JComboBox<String> cbbExpedicionPlanetaDestino1;
    private javax.swing.JComboBox<String> cbbPlanetaDestino;
    private javax.swing.JComboBox<String> cbbSexo;
    private javax.swing.JComboBox<String> cbbTipoNave;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAstro;
    private javax.swing.JButton jbGuardarAstro;
    private javax.swing.JButton jbGuardarPlaneta;
    private javax.swing.JButton jbModificarAstro;
    private javax.swing.JButton jbModificarPlaneta;
    private javax.swing.JButton jbPlaneta;
    private javax.swing.JButton jbPlaneta1;
    private javax.swing.JButton jbPlaneta2;
    private javax.swing.JDialog jdAstronautas;
    private javax.swing.JDialog jdPlaneta;
    private javax.swing.JMenuItem jmiEliminar;
    private javax.swing.JMenuItem jmiEliminar1;
    private javax.swing.JMenuItem jmiModificar;
    private javax.swing.JMenuItem jmiModificar1;
    private javax.swing.JPopupMenu ppMenuAstro;
    private javax.swing.JPopupMenu ppMenuPlanet;
    private javax.swing.JSpinner spDistancia;
    private javax.swing.JSpinner spIda1;
    private javax.swing.JSpinner spPeso;
    private javax.swing.JSpinner spPesoNave;
    private javax.swing.JSpinner spRegreso;
    private javax.swing.JSpinner spSueldo;
    private javax.swing.JSpinner spTemp;
    private javax.swing.JSpinner spVelocidadNave;
    private javax.swing.JTable tableAstronautas;
    private javax.swing.JTable tablePlanetas;
    private javax.swing.JTextField tfExperiencia;
    private javax.swing.JTextField tfLugarDespeje1;
    private javax.swing.JTextField tfMaterialNave;
    private javax.swing.JTextField tfNacionalidad;
    private javax.swing.JTextField tfNombreAstro;
    private javax.swing.JTextField tfNombrePlaneta;
    private javax.swing.JTextField tfNumeroDeSerie;
    private javax.swing.JTextField tfTipoSuperficie;
    // End of variables declaration//GEN-END:variables
    ArrayList<Planetas> Planetas = new ArrayList();
    ArrayList<Astronautas> Astronautas = new ArrayList();
    Planetas planetaseleccion;
    Astronautas astroseleccion;
    ArrayList<Naves> naves=new ArrayList();
}
